// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGDFJU4kGgp98taAdOnb7WkHum5sCKoEA',
    appId: '1:14269105254:web:6ae4904ac3ce4f570c19a7',
    messagingSenderId: '14269105254',
    projectId: 'flutterta-d3171',
    authDomain: 'flutterta-d3171.firebaseapp.com',
    storageBucket: 'flutterta-d3171.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTkon09NREsDeexROsUrdaRgsBMj1rnng',
    appId: '1:14269105254:android:da14b7bb935944390c19a7',
    messagingSenderId: '14269105254',
    projectId: 'flutterta-d3171',
    storageBucket: 'flutterta-d3171.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSKaA5IrkvMXlIbGypI_WrDidrd1xXYNE',
    appId: '1:14269105254:ios:8ef3d3c313d9d4a00c19a7',
    messagingSenderId: '14269105254',
    projectId: 'flutterta-d3171',
    storageBucket: 'flutterta-d3171.appspot.com',
    iosClientId: '14269105254-rf124g28316mvo9l3s2a19s0o82glh9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSKaA5IrkvMXlIbGypI_WrDidrd1xXYNE',
    appId: '1:14269105254:ios:a16420be1c5f4c720c19a7',
    messagingSenderId: '14269105254',
    projectId: 'flutterta-d3171',
    storageBucket: 'flutterta-d3171.appspot.com',
    iosClientId: '14269105254-2mm8r68fej1abkibgeovuvs4uc7vdug9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTa.RunnerTests',
  );
}
